### ISSUE TITLE
Propuesta de reestructuración de las ramas específicas.

### ISSUE THREAD

**Issue by davidhdz** [Comunidad-Tecnologia/malla-curricular#1]
Creo que sería conveniente cambiarle el nombre de aprendizaje automático a Inteligencia artificial, puesto que Aprendizaje Automático (_Machine learning_) es una rama de esta y nos da la oportunidad de agregar temas  como la programación genética, quedando de la siguiente forma:

- Inteligencia artificial
  - Inteligencia artificial
  - Redes neuronales
  - Aprendizaje automático 
  - Algoritmos genéticos

Adicionalmente movemos los sistemas de recomendación a la sección Minería de datos a la cual también sugiero cambiar el nombre a Análisis de datos o Análisis de sistemas, quedando de la siguiente forma y con oportunidad de añadir otros:

- Análisis de sistemas
  - Datos masivos
  - Minería de datos

Y podríamos abrir una nueva rama de Modelado y simulación para ubicar los temas de esa área que antes se encontraban en Minería de datos:

- Modelado y simulación
  - Estadística para simulación
  - Computación para simulación 
  - Modelado de sistemas complejos

**Comment by rudmanmrrod** [comment]
Me parece excelente, en un principio se planteó así de acuerdo a las áreas de nosotros, es decir las materias que necesitaba ver yo en "Aprendizaje Automático", las que necesitaba Leo en "Minería de datos", y luego Chuy en "Seguridad Informática", etc. Pero me parece excelente

**Comment by davidhdz** [comment]
Sí, mi propuesta en sí es una reorganización por área de los temas mostrados, con unas pocas adiciones.

**Comment by davidhdz** [comment]
Propuesta publicada.
